#!/bin/bash -xe

export WM_NCOMPPROCS=$(grep -c ^processor /proc/cpuinfo)

# ------------------------------------------------------------------------------
#
export OPENFOAM_DIR="/opt/openfoam"
export OPENFOAM_THIRDPARTY_DIR="$OPENFOAM_DIR/ThirdParty"

echo "export OPENFOAM_DIR=${OPENFOAM_DIR}" >> /etc/profile.d/buildenv.sh
echo "export OPENFOAM_THIRDPARTY_DIR=${OPENFOAM_THIRDPARTY_DIR}" >> /etc/profile.d/buildenv.sh

# ------------------------------------------------------------------------------
# load sources
git clone --branch $OPENFOAM_GIT_BRANCH            $OPENFOAM_GIT_URL            $OPENFOAM_DIR
git clone --branch $OPENFOAM_THIRDPARTY_GIT_BRANCH $OPENFOAM_THIRDPARTY_GIT_URL $OPENFOAM_THIRDPARTY_DIR

cd $OPENFOAM_DIR
git submodule init

echo ". $OPENFOAM_DIR/etc/bashrc" >> /etc/profile.d/openfoam.sh

# ------------------------------------------------------------------------------
# build openfoam

# ensure label size of 64 bit
#sed -ie  's|WM_LABEL_SIZE=32|WM_LABEL_SIZE=64|' ${OPENFOAM_DIR}/etc/bashrc

# config env
. /etc/profile.d/openfoam.sh || echo "skip errors."

# scotch
source $OPENFOAM_DIR/etc/config.sh/scotch
export SCOTCH_VERSION_NUMBER=$(echo $SCOTCH_VERSION | sed 's/^[^0-9]*//')
export SCOTCH_GIT_URL="https://gitlab.inria.fr/scotch/scotch.git"
export SCOTCH_GIT_BRANCH="v${SCOTCH_VERSION_NUMBER}"
export SCOTCH_DIR="${OPENFOAM_THIRDPARTY_DIR}/${SCOTCH_VERSION}"

echo "export SCOTCH_VERSION=${SCOTCH_VERSION}" >> /etc/profile.d/buildenv.sh
echo "export SCOTCH_VERSION_NUMBER=${SCOTCH_VERSION_NUMBER}" >> /etc/profile.d/buildenv.sh
echo "export SCOTCH_GIT_URL=${SCOTCH_GIT_URL}" >> /etc/profile.d/buildenv.
echo "export SCOTCH_GIT_BRANCH=${SCOTCH_GIT_BRANCH}" >> /etc/profile.d/buildenv.sh
echo "export SCOTCH_DIR=${SCOTCH_DIR}" >> /etc/profile.d/buildenv.sh

git clone --branch ${SCOTCH_GIT_BRANCH} ${SCOTCH_GIT_URL} ${SCOTCH_DIR}

#
cd ${OPENFOAM_THIRDPARTY_DIR}
./Allwmake

#
cd ${OPENFOAM_DIR}
./Allwmake -j -s -q -a

# ------------------------------------------------------------------------------
# cleanup openfoam

cd ${OPENFOAM_THIRDPARTY_DIR}
./Allclean

cd ${OPENFOAM_DIR}
#./Allclean
find -name '*.o' | xargs rm
find -name '*.dep' | xargs rm
#rm -rf build/*
