#!/bin/bash -xe

# ------------------------------------------------------------------------------
preCICE_adapter_BUILD_DIR=${preCICE_BUILD_DIR}
#preCICE_adapter_of_GIT_URL='https://github.com/precice/openfoam-adapter.git'
preCICE_adapter_of_GIT_URL='https://github.com/TEFEdotCC/openfoam-adapter.git'

#git clone ${preCICE_adapter_of_GIT_URL} ${preCICE_adapter_BUILD_DIR}/openfoam-adapter
git clone --branch CHT_WallHeatFlux ${preCICE_adapter_of_GIT_URL} ${preCICE_adapter_BUILD_DIR}/openfoam-adapter

# ------------------------------------------------------------------------------
cd ${preCICE_adapter_BUILD_DIR}/openfoam-adapter
sed -ie "s|ADAPTER_WMAKE_OPTIONS=\"|ADAPTER_WMAKE_OPTIONS=\"-j |" Allwmake
#sed -ie 's|-DADAPTER_DEBUG_MODE| |' Allwmake
sed -ie 's|${FOAM_USER_LIBBIN}|${FOAM_EXT_LIBBIN}|' Allwmake

./Allwmake
./Allclean
